### ISSUE TITLE
vAGRANT 2.1

### ISSUE THREAD

**Issue by karneaud** [akeeba/vagrant#14]
Do this work with Vagrant 2.1?

**Comment by nikosdion** [comment]
I do not see a reason why it shouldn't. However, I am developing and
testing this with Vagrant 2.0.2 on Ubuntu 18.04 LTS. Your mileage may
vary :)

**Comment by nikosdion** [comment]
I have an update. On my Mac I am using Vagrant 2.2.3 and it _does_ work. Since it works with both Vagrant 2.0 and 2.2 I will assume it does not have a problem with 2.1. Moreover, Vagrant follows semantic versioning, meaning that it _should_ work with all Vagrant 2.x versions.
