### ISSUE TITLE
Improvements to Joomla Install Extension CLI Tool

### ISSUE THREAD

**Issue by ZacharyDraper** [akeeba/vagrant#15]
Hi guys,

First off, thank you so much for your work on creating a CLI tool for installing Joomla! extensions. As we work to build a fully atomic Docker image for our Joomla! site, this has become invaluable.

In working with the CLI tool, we found that some packages would not install fully and were returning errors. This was primarily due to developers including unexpected function calls in their install scripts. As such, we have added some of the common ones to your CLI installer which resolved all of the issues we encountered. I wanted to share these functions with you so that you could include them if you so choose.

install-joomla-extension.php

```php
class JoomlaExtensionInstallerCli extends JApplicationCli
{
        ...

	/**
	 * Some packages call allowCache as part of their setup script to see if caching is allowed.
	 * Tell them no.
	 *
	 * @param boolean $allow
	 */
	public static function allowCache($allow)
	{
		return false;
	}

	/**
	 * Some components and packages will display detailed install messages.
	 * This will capture those messages, strip out the HTML and print them to the console.
	 *
	 * @param string $message
	 */
	public static function enqueueMessage($message)
	{
		(new self)->out(strip_tags($message));
	}

	/**
	 * Some component installers will redirect to their component after install.
	 * Since this is an anti-pattern that doesn't apply in CLI world, just ignore it.
	 *
	 * @param string $url
	 */
	public static function redirect($url)
	{
		return;
	}
}
```

Thanks again!

**Comment by nikosdion** [comment]
Thank you for the heads up! I took the liberty of correcting the code you submitted. None of these methods are static in Joomla's AdministratorApplication and WebApplication and a couple of method signatures were different. I changed them to prevent PHP 7 from throwing a fit when static methods are called non-static and there is a different number of arguments.
