### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by miljan-aleksic** [akeeba/vagrant#4]
Hi, first of all thanks for sharing this awesome configuration :)

I'm having some issues during Vagrant up:

- This one is not braking the code aparently, but it repeats all over:
```
stdin: is not a tty
```

Googling about seems some issue with Ubuntu and that could be solved (confirmed) with:

```
config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end
```

- This second issue happens when installing PEAR and stops the building:
```
==> devbox: spawn
==> devbox:  
==> devbox: /usr/bin/php
==> devbox:  
==> devbox: /vagrant/vagrant/downloads/go-pear.php
==> devbox: couldn't execute "/usr/bin/php": no such file or directory
==> devbox:     while executing
==> devbox: "spawn /usr/bin/php /vagrant/vagrant/downloads/go-pear.php"
==> devbox:     (file "/tmp/vagrant-shell" line 2)
```

I tried a lot of combinations and workarounds and before dropping the towel thought maybe you have some clue about it, which would very much appreciate. Thanks anyway :)

**Comment by nikosdion** [comment]
It sounds like the box could not download, compile or install PHP. I didn't have anything like that. Do you see anything amiss in the PHP compilation?

**Comment by miljan-aleksic** [comment]
Thanks for taking a look into this. I didn't see anything wrong with the PHP compilation the first time, but tried again enabling only php 5.4 and this is what I see now:

```
==> devbox: Installing XDebug (php54)
==> devbox: cp: 
==> devbox: cannot stat ‘/usr/local/src/xdebug-php54/modules/xdebug.so’
==> devbox: : No such file or directory
==> devbox: Done installing XDebug (php54)
```

**Comment by nikosdion** [comment]
Try removing all generated files and rebuild the VM

**Comment by miljan-aleksic** [comment]
Yep, that solved it. There are still some issues around, but I think I'll handle it. Thank you very much :)

**Comment by nikosdion** [comment]
You're welcome :)
