### ISSUE TITLE
no connection ssh

### ISSUE THREAD

**Issue by 810** [akeeba/vagrant#6]
==> devbox: Waiting for machine to boot. This may take a few minutes...
    devbox: SSH address: 127.0.0.1:2222
    devbox: SSH username: vagrant
    devbox: SSH auth method: private key
    devbox: Warning: Connection refused. Retrying...
    devbox: Warning: Connection refused. Retrying...

**Comment by nikosdion** [comment]
Nothing to do with our configuration. See http://stackoverflow.com/questions/30524685/vagrant-virtualbox-not-connecting-connection-refused-retrying
